from enum import Enum


class USTContractField(Enum):
    con_id = "conid"
    currency = "currency"
    ticker = "ticker"
    bond_name = "bondName"
    full_name = "fullName"
    desc_label = "descLabel"
    country_of_issue = "countryOfIssue"
    principal_value = "principalValue"
    issue_date = "issueDate"
    maturity_date = "maturityDate"
    pay_principal_on_maturity = "payPrincipalOnMaturity"
    bb_mkt_lss = "bbMktIss"
    coupon_rate = "rate"
    coupon_first_date = "firstDate"
    coupon_first_accr_date = "firstAccrDate"
    coupon_prev_date = "prevDate"
    coupon_second_date = "secondDate"
    coupon_ncpdt = "ncpdt"
    coupon_cpc = "cpc"
    si_id = "id"
    cusip = "cusip"
    increment = "increment"
    increment_lower_edge = "lowerEdge"
    issue_amount = "issueAmount"
    open_amount = "openAmount"
    initial_price = "initialPrice"
    year_to_maturity = "year_to_maturity"
